-- local log = require("log")
--
-- log.trace("Loading Anchor...")
--
-- local Anchor = {
-- 	new = function(buffer_id, file_path)
-- 		log.trace("Anchor.new(buffer_id =", buffer_id, ", file_path =", file_path, ")")
-- 		if file_path == "" then
-- 			file_path = "[No Name]"
-- 		end
--
-- 		return { buffer_id = buffer_id, file_path = file_path }
-- 	end,
-- }
--
-- local AnchorList = {
-- 	list = {},
--
-- 	append = function(self, anchor)
-- 		log.trace("AnchorList.append(", anchor, ")")
-- 		table.insert(self.list, anchor)
-- 	end,
--
-- 	length = function(self)
-- 		return #self.list
-- 	end,
--
-- 	iter = function(self)
-- 		return ipairs(self.list)
-- 	end,
--
-- 	clear = function(self)
-- 		self.list = {}
-- 	end,
-- }
--
-- local anchor = function(buffer_id)
-- 	log.trace("anchor(buffer_id =", buffer_id, ")")
-- 	for _, anchor in AnchorList:iter() do
-- 		if buffer_id == anchor.buffer_id then
-- 			log.info("Buffer already anchored")
-- 			return
-- 		end
-- 	end
--
-- 	local file_path = vim.fn.expand("%:.")
-- 	local anchor = Anchor.new(buffer_id, file_path)
-- 	AnchorList:append(anchor)
-- end
--
-- local anchor_list = function()
-- 	if AnchorList:length() == 0 then
-- 		log.info("Anchor list is empty")
-- 		return
-- 	end
--
-- 	local message = ""
--
-- 	for _, anchor_item in AnchorList:iter() do
-- 		message = message .. ("[" .. anchor_item.buffer_id .. "] " .. anchor_item.file_path .. "\n")
-- 	end
--
-- 	print(message)
-- 	log.info(message)
-- end
--
-- vim.api.nvim_create_user_command("Anchor", anchor, { nargs = 0 })
--
-- vim.api.nvim_create_user_command("AnchorList", anchor_list, { nargs = 0 })
--
-- local anchor_rest = function()
-- 	AnchorList:clear()
-- end
--
-- vim.api.nvim_create_user_command("AnchorReset", anchor_rest, { nargs = 0 })
--
-- local on_new_buffer = function()
-- 	log.trace("on_new_buffer()")
-- 	local buffer_id = vim.api.nvim_get_current_buf()
-- 	local buftype = vim.api.nvim_get_option_value("buftype", { buf = buffer_id })
-- 	local buf_name = vim.api.nvim_buf_get_name(buffer_id)
--
-- 	log.trace("Buffer { buffer_id =", buffer_id, ", buftype =", buftype, ", buf_name =", buf_name, " }")
-- 	if buftype == "" and buf_name ~= "" then
-- 		anchor(buffer_id)
-- 	end
-- end
--
-- -- vim.api.nvim_create_autocmd("VimEnter", {
-- -- 	callback = on_new_buffer,
-- -- 	desc = "Anchor buffer",
-- -- })
--
-- vim.api.nvim_create_autocmd("BufNew", {
-- 	callback = on_new_buffer,
-- 	desc = "Anchor buffer",
-- })
--
-- vim.keymap.set("n", "<Leader>b", anchor_list, { desc = "Show anchor list" })
