--- @diagnostic disable unused-local -- autogenerated

local theme = {
	inactive = {
		a = { bg = palette.mantle, fg = palette.subtext0 },
		b = { bg = palette.mantle, fg = palette.overlay0 },
		c = { bg = palette.mantle, fg = palette.subtext0 },
	},
	normal = {
		a = { bg = palette.lavender, fg = palette.base, gui = "bold" },
		b = { bg = palette.crust, fg = palette.subtext1 },
		c = { bg = palette.mantle, fg = palette.subtext1 },
	},
	command = {
		a = { bg = palette.lavender, fg = palette.base, gui = "bold" },
	},
	insert = {
		a = { bg = palette.maroon, fg = palette.base, gui = "bold" },
	},
	visual = {
		a = { bg = palette.mauve, fg = palette.base, gui = "bold" },
	},
	replace = {
		a = { bg = palette.yellow, fg = palette.base, gui = "bold" },
	},
}
