local palette = require("catppuccin.palettes").get_palette("mocha")

--- @diagnostic disable-next-line: unused-local -- autogenerated
local colors = {
	-- inactive
	inactive_a_bg = palette.mantle,
	inactive_a_fg = palette.subtext0,
	inactive_b_bg = palette.mantle,
	inactive_b_fg = palette.overlay0,
	inactive_c_bg = palette.mantle,
	inactive_c_fg = palette.subtext0,

	-- normal
	normal_a_bg = palette.lavender,
	normal_a_fg = palette.base,
	normal_b_bg = palette.crust,
	normal_b_fg = palette.subtext1,
	normal_c_bg = palette.mantle,
	normal_c_fg = palette.subtext1,

	-- command
	command_a_bg = palette.lavender,
	command_a_fg = palette.base,

	-- insert
	insert_a_bg = palette.maroon,
	insert_a_fg = palette.base,

	-- visual
	visual_a_bg = palette.mauve,
	visual_a_fg = palette.base,

	-- replace
	replace_a_bg = palette.yellow,
	replace_a_fg = palette.base,
}
-- >>> theme marker <<< --
-- Anything above this is autogenerated (see ~/.config/theme/scripts/set-nvim-theme.sh)

local function macro_recording_status()
	local recording_register = vim.fn.reg_recording()
	if recording_register ~= "" then
		return "recording @" .. recording_register
	end
	return ""
end

require("lualine").setup({
	options = {
		theme = {
			inactive = {
				a = { bg = colors.inactive_a_bg, fg = colors.inactive_a_fg },
				b = { bg = colors.inactive_b_bg, fg = colors.inactive_b_fg },
				c = { bg = colors.inactive_c_bg, fg = colors.inactive_c_fg },
			},
			normal = {
				a = { bg = colors.normal_a_bg, fg = colors.normal_a_fg, gui = "bold" },
				b = { bg = colors.normal_b_bg, fg = colors.normal_b_fg },
				c = { bg = colors.normal_c_bg, fg = colors.normal_c_fg },
			},
			command = {
				a = { bg = colors.command_a_bg, fg = colors.command_a_fg, gui = "bold" },
			},
			insert = {
				a = { bg = colors.insert_a_bg, fg = colors.insert_a_fg, gui = "bold" },
			},
			visual = {
				a = { bg = colors.visual_a_bg, fg = colors.visual_a_fg, gui = "bold" },
			},
			replace = {
				a = { bg = colors.replace_a_bg, fg = colors.replace_a_fg, gui = "bold" },
			},
		},
		component_separators = { left = "", right = "" },
		section_separators = { left = "", right = "" },
		disabled_filetypes = {
			statusline = {},
			winbar = {},
		},
		ignore_focus = {},
		always_divide_middle = true,
		always_show_tabline = true,
		globalstatus = false,
		refresh = {
			statusline = 100,
			tabline = 100,
			winbar = 100,
		},
	},
	sections = {
		lualine_a = {
			{
				"mode",
				padding = 2,
				fmt = function(str)
					local mode = str:sub(1, 3)
					-- Command line covers Normal mode, prevent glitch
					if mode == "COM" then
						return "NOR"
					end
					return mode
				end,
			},
		},
		lualine_b = {
			-- {
			-- 	"buffers",
			-- 	icons_enabled = false,
			-- 	symbols = {
			-- 		alternate_file = "✦",
			-- 	},
			-- },
		},
		lualine_c = {
			{
				"filename",
				file_status = true, -- Displays file status (readonly status, modified status)
				newfile_status = false, -- Display new file status (new file means no write after created)
				path = 1, -- 0: Just the filename
				-- 1: Relative path
				-- 2: Absolute path
				-- 3: Absolute path, with tilde as the home directory
				-- 4: Filename and parent dir, with tilde as the home directory

				shorting_target = 40, -- Shortens path to leave 40 spaces in the window
				-- for other components. (terrible name, any suggestions?)
				symbols = {
					modified = "●", -- Text to show when the file is modified.
					readonly = "[RO]", -- Text to show when the file is non-modifiable or readonly.
					unnamed = "[No Name]", -- Text to show for unnamed buffers.
					newfile = "[New]", -- Text to show for newly created file before first write
				},
			},
		},

		lualine_x = {
			macro_recording_status,
			"diff",
			{
				"diagnostics",
				symbols = { error = "E:", warn = "W:", info = "I:", hint = "H:" },
			},
			"branch",
			"progress",
			"location",
		},
		lualine_y = {},
		lualine_z = {},
	},
	inactive_sections = {
		lualine_a = {},
		lualine_b = {},
		lualine_c = {},
		lualine_x = {},
		lualine_y = {},
		lualine_z = {},
	},
	tabline = {},
	winbar = {},
	inactive_winbar = {},
	extensions = {},
})
