--- @diagnostic disable-next-line: unused-local -- autogenerated
local palette = require("catppuccin.palettes").get_palette("mocha")
--- @diagnostic disable unused-local -- autogenerated

local theme = {
	inactive = {
		a = { bg = palette.mantle, fg = palette.subtext0 },
		b = { bg = palette.mantle, fg = palette.overlay0 },
		c = { bg = palette.mantle, fg = palette.subtext0 },
	},
	normal = {
		a = { bg = palette.lavender, fg = palette.base, gui = "bold" },
		b = { bg = palette.crust, fg = palette.subtext1 },
		c = { bg = palette.mantle, fg = palette.subtext1 },
	},
	command = {
		a = { bg = palette.lavender, fg = palette.base, gui = "bold" },
	},
	insert = {
		a = { bg = palette.maroon, fg = palette.base, gui = "bold" },
	},
	visual = {
		a = { bg = palette.mauve, fg = palette.base, gui = "bold" },
	},
	replace = {
		a = { bg = palette.yellow, fg = palette.base, gui = "bold" },
	},
}
-- >>> theme marker <<< --
-- Anything above this is autogenerated (see ~/.config/theme/scripts/set-nvim-theme.sh)

local function macro_recording_status()
	local recording_register = vim.fn.reg_recording()
	if recording_register ~= "" then
		return "recording @" .. recording_register
	end
	return ""
end

require("lualine").setup({
	options = {
		theme = theme,
		component_separators = { left = "", right = "" },
		section_separators = { left = "", right = "" },
		disabled_filetypes = {
			statusline = {},
			winbar = {},
		},
		ignore_focus = {},
		always_divide_middle = true,
		always_show_tabline = true,
		globalstatus = false,
		refresh = {
			statusline = 100,
			tabline = 100,
			winbar = 100,
		},
	},
	sections = {
		lualine_a = {
			{
				"mode",
				padding = 2,
				fmt = function(str)
					local mode = str:sub(1, 3)
					return mode
				end,
			},
		},
		lualine_b = {
			-- {
			-- 	"buffers",
			-- 	icons_enabled = false,
			-- 	symbols = {
			-- 		alternate_file = "✦",
			-- 	},
			-- },
		},
		lualine_c = {
			{
				"filename",
				file_status = true, -- Displays file status (readonly status, modified status)
				newfile_status = false, -- Display new file status (new file means no write after created)
				path = 1, -- 0: Just the filename
				-- 1: Relative path
				-- 2: Absolute path
				-- 3: Absolute path, with tilde as the home directory
				-- 4: Filename and parent dir, with tilde as the home directory

				shorting_target = 40, -- Shortens path to leave 40 spaces in the window
				-- for other components. (terrible name, any suggestions?)
				symbols = {
					modified = "●", -- Text to show when the file is modified.
					readonly = "[RO]", -- Text to show when the file is non-modifiable or readonly.
					unnamed = "[No Name]", -- Text to show for unnamed buffers.
					newfile = "[New]", -- Text to show for newly created file before first write
				},
			},
		},

		lualine_x = {
			{ "overseer", unique = true },
			macro_recording_status,
			"diff",
			{
				"diagnostics",
				symbols = { error = "E:", warn = "W:", info = "I:", hint = "H:" },
			},
			"branch",
			"progress",
			"location",
		},
		lualine_y = {},
		lualine_z = {},
	},
	inactive_sections = {
		lualine_a = {},
		lualine_b = {},
		lualine_c = {},
		lualine_x = {},
		lualine_y = {},
		lualine_z = {},
	},
	tabline = {},
	winbar = {},
	inactive_winbar = {},
	extensions = {},
})
