# remap prefix from 'C-b' to '`'
unbind C-b
set-option -g prefix `
bind Tab send-prefix

# Support 256 color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
# undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
# support colors for undercurl
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Remove delay when pressing <escape> in vim
set -s escape-time 0

# keep session alive even with no windows
set -g detach-on-destroy off

# Enable mouse mode
set -g mouse on

# set vi bindings in copy mode
set -g mode-keys  vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'

set-option -wg automatic-rename on
set-option -wg automatic-rename-format '#{pane_current_command}'

# disable interval
set -g status-interval 0

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1

# reload config file
bind "C-r" source-file ~/.config/tmux/tmux.conf
# toggle status bar
bind-key b set-option status

unbind '"'
unbind %
unbind f
unbind x

# ====== PANES ======

# split panes using | and -
bind - split-window -c "#{pane_current_path}" -v -l 30%
bind \\ split-window -c "#{pane_current_path}" -h -l 30%

# Focus panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Resize panes
bind -n M-Left resize-pane -L
bind -n M-Down resize-pane -D
bind -n M-Up resize-pane -U
bind -n M-Right resize-pane -R

bind-key x kill-pane
bind C-l clear-history

# ====== WINDOW =====

bind t new-window
bind T new-window -c "#{pane_current_path}"

bind-key p previous-window
bind-key n next-window


# ==== STATUS BAR ====

set -g status-left " [#(echo $(tmux list-sessions | grep -n '^' | grep $(tmux display-message -p '#S') | cut -d: -f1)/$(tmux list-sessions | wc -l | xargs))]"
set -g status-left-length 90
set -g status-right "[#S] "
set -g status-right-length 90
set -g status-interval 0
set -g status-justify absolute-centre
setw -g window-status-current-format '#{?window_zoomed_flag,#[fg=yellow](,}#I.#W#{?window_zoomed_flag,#[fg=yellow]),}'
setw -g window-status-format '#{?window_zoomed_flag,(,}#I.#W#{?window_zoomed_flag,),}'

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1

# ====== POPUP ======

set -g popup-border-line rounded

# Custom Shell Scripts

bind-key r run-shell -b "tmux display-popup -E 'fish -c select-tmux-session'"
bind-key g run-shell -b "editor-git"
bind-key e run-shell -b "edit-tmux-pane-output"
bind-key E run-shell -b "edit-tmux-pane-output --scrollback"

# Configuration after the marker below is generated by `~/.config/theme`

# >>> THEME MARKER <<< #
set -g pane-border-style fg="#5b6078"
set -g pane-active-border-style fg="#b4befe"

set -g status-bg "#1e1e2e" # mocha base
set -g status-fg "#6c7086" # mocha overlay 0
set-window-option -g window-status-current-style fg="#a5adce" # mocha subtext 0

