local palette = require("catppuccin.palettes").get_palette("latte")

--- @diagnostic disable-next-line: unused-local -- autogenerated
local colors = {
	-- inactive
	inactive_a_bg = palette.mantle,
	inactive_a_fg = palette.subtext0,
	inactive_b_bg = palette.mantle,
	inactive_b_fg = palette.overlay0,
	inactive_c_bg = palette.mantle,
	inactive_c_fg = palette.subtext0,

	-- normal
	normal_a_bg = palette.lavender,
	normal_a_fg = palette.base,
	normal_b_bg = palette.crust,
	normal_b_fg = palette.subtext1,
	normal_c_bg = palette.mantle,
	normal_c_fg = palette.subtext1,

	-- command
	command_a_bg = palette.lavender,
	command_a_fg = palette.base,

	-- insert
	insert_a_bg = palette.maroon,
	insert_a_fg = palette.base,

	-- visual
	visual_a_bg = palette.mauve,
	visual_a_fg = palette.base,

	-- replace
	replace_a_bg = palette.yellow,
	replace_a_fg = palette.base,
}
