"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [0, 1, 2]
show_symlink = false

[opener]
edit = [
	{ run = 'nvr "$@"', desc = "$EDITOR", block = false, for = "unix" },
]

# ~/.config/yazi/yazi.toml
[[opener.bulk-rename]]
run   = 'nvim "$@"'
block = true

[[open.prepend_rules]]
name = "bulk-rename.txt"
use  = "bulk-rename"
