[mgr]
ratio = [0, 1, 2]
show_symlink = false

[opener]
edit = [
	{ run = 'nvr "$@"', desc = "$EDITOR", block = false, for = "unix" },
]

# ~/.config/yazi/yazi.toml
[[opener.bulk-rename]]
run   = 'nvim "$@"'
block = true

[[open.prepend_rules]]
url = "bulk-rename.txt"
use = "bulk-rename"

[preview]
max_width = 1500
max_height = 4500
