theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
soft-wrap.enable = true

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.statusline]
right = [
    "version-control",
    "spacer",
    "separator",
    "diagnostics",
    "workspace-diagnostics",
    "register",
    "file-encoding",
    "separator",
    "position",
    "position-percentage",
    "total-line-numbers",
]
#version-control = "right"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
# H = "goto_line_start"
# L = "goto_line_end"
# G = "goto_last_line"
esc = ["collapse_selection", "keep_primary_selection"]
C-e = "scroll_down"
C-y = "scroll_up"

ret = ["open_below", "normal_mode"]
"\\" = ["open_above", "normal_mode"]

backspace = { r = ":config-reload" }

[keys.select]
G = ["extend_line_below", "goto_last_line", "goto_line_end"]
# H = "goto_line_start"
# L = "goto_line_end"

[keys.insert]
C-p = "move_line_up"
C-n = "move_line_down"
C-e = "goto_line_end_newline"
C-a = "goto_line_start"
C-f = "move_char_right"
C-b = "move_char_left"
C-u = [
    "move_prev_word_start",
    "move_next_word_end",
    "switch_case",
    "move_char_right",
]
