[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "yaml"] }

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer"]
formatter = { command = "rustfmt", args = ["--edition", "2021"] }


[[language]]
name = "lua"
auto-format = true
language-servers = ["lua-language-server"]
formatter = { command = "lua-language-server" }


[language-server.rust-analyzer]
command = "rust-analyzer"
config = { check = { command = "clippy" } }
